<?php

use App\Http\Controllers\AccountController;
use App\Http\Controllers\BannerController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\GameController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\RegisterController;
use App\Http\Controllers\TransactionController;
use App\Http\Controllers\PaymentController;
use App\Http\Middleware\AdminMiddleware;
use App\Http\Middleware\MemberMiddleware;

Route::get('/profile', [AccountController::class, 'index'])->middleware(AdminMiddleware::class);
Route::post('/profile/updateCompany', [AccountController::class, 'updateCompany'])->name('update.company')->middleware(AdminMiddleware::class);
Route::post('/profile/updateMedsos', [AccountController::class, 'updateMedsos'])->name('update.medsos')->middleware(AdminMiddleware::class);
Route::get('/banner', [BannerController::class, 'index'])->middleware(AdminMiddleware::class);
Route::post('/banner', [BannerController::class, 'index'])->middleware(AdminMiddleware::class);
Route::post('/banner', [BannerController::class, 'update'])->name('banner.update');
Route::get('/payment', [PaymentController::class, 'index'])->middleware(AdminMiddleware::class);
Route::post('/payment', [PaymentController::class, 'updateStatus'])->middleware(AdminMiddleware::class);
Route::delete('/payments/{id}', [PaymentController::class, 'destroy'])->name('payments.destroy');
Route::get('/payment/{payment:slug}/edit', [PaymentController::class, 'edit'])->middleware(AdminMiddleware::class);
Route::post('/payment/{payment:slug}/edit', [PaymentController::class, 'update'])->middleware(AdminMiddleware::class);
Route::post('/items/{id}/set-discount', [PaymentController::class, 'setDiscount'])->name('items.setDiscount');
Route::post('/items/{id}/remove-discount', action: [PaymentController::class, 'removeDiscount'])->name('items.removeDiscount');
Route::get('/revenue', [TransactionController::class, 'revenue'])->middleware(AdminMiddleware::class);
Route::get('/transaksi', [TransactionController::class, 'nota'])->middleware(AdminMiddleware::class);
Route::post('/transaksi/{id}', [TransactionController::class, 'transaksiadmin'])->name('update.status')->middleware(AdminMiddleware::class);
Route::get('/nota/{id_transaksi}', [TransactionController::class, 'nota'])->name('nota');
Route::get('/cari-pesanan', [TransactionController::class,'getNota'])->name('search.transaction');
Route::get('/login', [LoginController::class, 'index'])->middleware('guest');
Route::post('/login', [LoginController::class, 'store']);
Route::get('/logout', [LoginController::class, 'logout'])->middleware('auth');
Route::get('/register', [RegisterController::class, 'index'])->middleware('guest');
Route::post('/register', [RegisterController::class, 'store']);
Route::get('/{game:slug}/edit', [GameController::class, 'edit'])->middleware(AdminMiddleware::class);
Route::post('/{game:slug}/edit', [GameController::class, 'update'])->name('update.game')->middleware(AdminMiddleware::class);
Route::get('/', [GameController::class, 'index']);
Route::post('/', [GameController::class, 'upload']);
Route::get('/{game:slug}', [GameController::class, 'detail'])->name('backToGame');
Route::post('/{game:slug}', [TransactionController::class, 'store'])->middleware(MemberMiddleware::class);