<?php

use App\Http\Controllers\AccountController;
use App\Http\Controllers\BannerController;
use App\Http\Controllers\ContactController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\GameController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\RegisterController;
use App\Http\Controllers\TransactionController;
use App\Http\Controllers\PaymentController;
use App\Http\Middleware\AdminMiddleware;
use App\Http\Middleware\MemberMiddleware;
Route::get('/contact', [ContactController::class, 'index']);

Route::get('/contact/{activity:request_id}', [ContactController::class, 'detail'])->name('detail.message');
Route::post('/contact', [ContactController::class, 'store'])->name('contact.message');
Route::post('/contact/{id}', [ContactController::class, 'updateStatus'])->name('update.status.message');
Route::post('/contact/{id}/reply', [ContactController::class, 'replyMessage'])->name('reply.message');
Route::get('/profile', [AccountController::class, 'index']);
Route::post('/profile', [AccountController::class, 'updateCompany'])->name('update.company');
Route::post('/profile/{id}/update-user', [AccountController::class, 'updateUserInfo'])->name('update.user.info')->middleware('auth');
Route::delete('/profile/{id}/destroy-user', [AccountController::class, 'destroyUser'])->name('user.destroy')->middleware('auth');
Route::post('/profile/updatePassword', [AccountController::class, 'updatePassword'])->name('update.password')->middleware('auth');
Route::get('/banner', [BannerController::class, 'index'])->middleware(AdminMiddleware::class);
Route::post('/banner', [BannerController::class, 'index'])->middleware(AdminMiddleware::class);
Route::post('/banner', [BannerController::class, 'update'])->name('banner.update');
Route::get('/payment', [PaymentController::class, 'index'])->middleware(AdminMiddleware::class);
Route::post('/payment', [PaymentController::class, 'updateStatus'])->middleware(AdminMiddleware::class);
Route::delete('/payments/{id}', [PaymentController::class, 'destroy'])->name('payments.destroy');
Route::get('/payment/{payment:slug}/edit', [PaymentController::class, 'edit'])->middleware(AdminMiddleware::class);
Route::post('/payment/add', [PaymentController::class, 'upload'])->middleware(AdminMiddleware::class)->name('payment.upload');
Route::post('/payment/{payment:slug}/edit', [PaymentController::class, 'update'])->middleware(AdminMiddleware::class);
Route::post('/items/{id}/set-discount', [PaymentController::class, 'setDiscount'])->name('items.setDiscount');
Route::post('/items/{id}/remove-discount', action: [PaymentController::class, 'removeDiscount'])->name('items.removeDiscount');
Route::post('/items/{id}/set-coins',  [PaymentController::class, 'setCoins'])->name('items.setCoins');
Route::post('/items/{id}/remove-coins', action: [PaymentController::class, 'removeCoins'])->name('items.deleteCoins');
Route::get('/revenue', [TransactionController::class, 'revenue'])->middleware(AdminMiddleware::class);
Route::get('/transaksi', [TransactionController::class, 'transaksi']);
Route::post('/transaksi/{id}', [TransactionController::class, 'transaksiadmin'])->name('update.status')->middleware(AdminMiddleware::class);
Route::get('/nota/{id_transaksi}', [TransactionController::class, 'nota'])->name('nota');
Route::post('/nota/{id}', [TransactionController::class, 'bukti'])->name('bukti.upload');
Route::post('/cari-pesanan', [TransactionController::class, 'bukti']);
Route::get('/cari-pesanan', [TransactionController::class,'getNota'])->name('search.transaction');
Route::get('/login', [LoginController::class, 'index'])->middleware('guest');
Route::post('/login', [LoginController::class, 'store']);
Route::get('/logout', [LoginController::class, 'logout']);
Route::get('/register', [RegisterController::class, 'index'])->middleware('guest');
Route::post('/register', [RegisterController::class, 'store']);
Route::get('/{game:slug}/edit', [GameController::class, 'edit'])->middleware(AdminMiddleware::class);
Route::post('/{game:slug}/edit', [GameController::class, 'update'])->name('update.game')->middleware(AdminMiddleware::class);
Route::get('/', [GameController::class, 'index']);
Route::post('/', [GameController::class, 'upload']);
Route::get('/{game:slug}', [GameController::class, 'detail'])->name('backToGame');
Route::post('/{game:slug}', [TransactionController::class, 'store'])->middleware(MemberMiddleware::class);
